version: '3'
services:
  notebook:
    build:
      context: .
      args:
        UID: 1001
        GID: 1001
    container_name: my-notebook
    ports:
     - "8888:8888"
    volumes:
     - ~/nbs:/nbs
    command: "jupyter notebook"
